### PR TITLE
Update to Node 20

### PR DESCRIPTION
**Pull request by palday**
This seems to be necessary for compatibility with setup-julia v2

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Just FYI, in the GitHub Actions ecosystem, this kind of change (upgrading from `node16` to `node20`) is considered a breaking change, which is why I believe the new release should be `v2`.

Some examples of official actions that made a breaking release (bumped the major version number) when they upgraded from `node16` to `node20`:
1. `actions/checkout` went from `v3` to `v4`: https://github.com/actions/checkout/releases/tag/v4.0.0
2. `actions/cache` went from `v3` to `v4`: https://github.com/actions/cache/releases/tag/v4.0.0

**Comment by DilumAluthge** [comment]
@palday Are you okay with me doing the following steps?
1. Point the `v1` tag back to `v1.1.2`
2. Delete the `v1.1.3` tag
3. Make a new `v2.0.0` tag
4. Make a new `v2` tag that points to `v2.0.0`

**Comment by palday** [comment]
@DilumAluthge I have no objections

**Comment by DilumAluthge** [comment]
I'll perform those steps now.

**Comment by DilumAluthge** [comment]
I have completed the above steps.

**Pull request merged**
