### PR TITLE
Avoid cloning cached registries

### PR DESCRIPTION
**Pull request by omus**
Depends on:
- #22

Fixes:
- https://github.com/julia-actions/add-julia-registry/issues/19 (when using `julia-actions/cache` before this action with `cache-registries: true`. Enabled by default in `julia-actions/cache@v1.5.0`)

Moves away from cloning to a temporary directory in order to interact better with `julia-actions/cache` when registry cloning is enabled. The key component here is to use a consistent name of the registry such that we know the repo has already been downloaded and we can skip an additional clone. In order to do this I've opted to clone the registry using the repo name into the depot registry directory. As some registries can have different registry names from repo names I've added a symlink into the depot registry as well such that both names co-exist. 

Luckily, Julia is smart enough to avoid updating both registries. For example:
```sh
❯ mkdir -p /tmp/julia-depot/registries

❯ cd /tmp/julia-depot/registries

❯ export JULIA_DEPOT_PATH=/tmp/julia-depot

❯ git clone https://github.com/JuliaRegistries/General
Cloning into 'General'...
remote: Enumerating objects: 792384, done.
remote: Counting objects: 100% (11484/11484), done.
remote: Compressing objects: 100% (769/769), done.
remote: Total 792384 (delta 10868), reused 11214 (delta 10711), pack-reused 780900
Receiving objects: 100% (792384/792384), 230.00 MiB | 35.60 MiB/s, done.
Resolving deltas: 100% (432024/432024), done.
Updating files: 100% (42228/42228), done.

❯ ln -s General GeneralSymlink

❯ julia -e 'using Pkg; Pkg.Registry.update()'
    Updating registry at `/tmp/julia-depot/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General`

❯ rm GeneralSymlink

❯ ln -s General 1-GeneralSymlink

❯ julia -e 'using Pkg; Pkg.Registry.update()'
    Updating registry at `/tmp/julia-depot/registries/1-GeneralSymlink`
    Updating git-repo `https://github.com/JuliaRegistries/General`

❯ julia-1.6 -e 'using Pkg; Pkg.Registry.update()'
    Updating registry at `/tmp/julia-depot/registries/1-GeneralSymlink`
    Updating git-repo `https://github.com/JuliaRegistries/General`
```

### CODE REVIEW

**Comment by omus** [comment]
Uncovered a performance issue while testing this against a real workflow. The `getRegistryName` function now parses the `General/Registry.toml` file which is only 929K at the time I write this but this parsing can take over 4 minutes :(. The toml package has a related issue but it's old enough that I'm doubtful we can have proper fix: https://github.com/BinaryMuse/toml-node/issues/39

**Comment by omus** [comment]
Note that Julia seems to be keeping track of registry URLs it has updated and there isn't any symlink specific logic:
```sh
❯  mkdir -p /tmp/julia-depot2/registries

❯ cd /tmp/julia-depot2/registries

❯ export JULIA_DEPOT_PATH=/tmp/julia-depot2

❯ git clone https://github.com/JuliaRegistries/General General1
Cloning into 'General1'...
remote: Enumerating objects: 792469, done.
remote: Counting objects: 100% (12926/12926), done.
remote: Compressing objects: 100% (492/492), done.
remote: Total 792469 (delta 12567), reused 12681 (delta 12433), pack-reused 779543
Receiving objects: 100% (792469/792469), 229.36 MiB | 29.74 MiB/s, done.
Resolving deltas: 100% (432253/432253), done.
Updating files: 100% (42240/42240), done.

❯ git clone https://github.com/JuliaRegistries/General General2
Cloning into 'General2'...
remote: Enumerating objects: 792469, done.
remote: Counting objects: 100% (13033/13033), done.
remote: Compressing objects: 100% (846/846), done.
remote: Total 792469 (delta 12363), reused 12761 (delta 12183), pack-reused 779436
Receiving objects: 100% (792469/792469), 230.05 MiB | 34.76 MiB/s, done.
Resolving deltas: 100% (432061/432061), done.
Updating files: 100% (42240/42240), done.

❯ julia -e 'using Pkg; Pkg.Registry.update()'
    Updating registry at `/tmp/julia-depot2/registries/General1`
    Updating git-repo `https://github.com/JuliaRegistries/General`
```

**Comment by omus** [comment]
Validated that these changes work in a private workflow.

**Review by IanButterworth — APPROVED** [review]

**Comment by omus** [comment]
I've validated the merge commit works in a private workflow

**Pull request merged**
